version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: >-
            apt-get update &&
            apt-get install -y git mercurial curl gcc make automake autoconf libtool cmake g++ pkg-config bison flex &&
            apt-get install -y libfontconfig1-dev libfreetype6-dev libbz2-dev librubberband-dev libfftw3-dev
      - run:
          name: Building
          command: ./build_ffmpeg.sh
